version: '3'
services:
  nacos:
    image: zhusaidong/nacos-server-m1:2.0.3
    container_name: nacos-server
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - 8848:8848
      - 9848:9848
    volumes:
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    restart: always