services:
  nacos1:
    image: zhusaidong/nacos-server-m1:2.0.3
    container_name: nacos1
    hostname: nacos1
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=cluster
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
      - JVM_XMS=1g
      - JVM_XMX=1g
      - JVM_XMN=512m
      - NACOS_APPLICATION_PORT=8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      - NACOS_AUTH_IDENTITY_KEY=nacos2023
      - NACOS_AUTH_IDENTITY_VALUE=nacos2023
      - NACOS_AUTH_TOKEN=SecretKey345901234567890126785678901234567890123901234567890123445678
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"

  nacos2:
    image: zhusaidong/nacos-server-m1:2.0.3
    container_name: nacos2
    hostname: nacos2
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=cluster
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
      - JVM_XMS=1g
      - JVM_XMX=1g
      - JVM_XMN=512m
      - NACOS_APPLICATION_PORT=8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      - NACOS_AUTH_IDENTITY_KEY=nacos2023
      - NACOS_AUTH_IDENTITY_VALUE=nacos2023
      - NACOS_AUTH_TOKEN=SecretKey345901234567890126785678901234567890123901234567890123445678
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "8849:8848"
      - "9849:9848"

  nacos3:
    image: zhusaidong/nacos-server-m1:2.0.3
    container_name: nacos3
    hostname: nacos3
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=cluster
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
      - JVM_XMS=1g
      - JVM_XMX=1g
      - JVM_XMN=512m
      - NACOS_APPLICATION_PORT=8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      - NACOS_AUTH_IDENTITY_KEY=nacos2023
      - NACOS_AUTH_IDENTITY_VALUE=nacos2023
      - NACOS_AUTH_TOKEN=SecretKey345901234567890126785678901234567890123901234567890123445678
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
    ports:
      - "8850:8848"
      - "9850:9848"

  mysql:
    image: mariadb:10.6
    container_name: mysql-nacos
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    volumes:
      - ./mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  default:
    name: nacos_net
    driver: bridge